---

# ansible_slackware_bootstrap
#
# File: slackware-admin-setup.yaml
# Version 1.0
# Copyright Joey Kelly (joeykelly.net)
# March 9, 2016
# License: GPL version 2
#
# https://github.com/mmlj4/ansible_slackware_bootstrap


# we need to set up basic admin stuff on a slackware box
#
# NOTE: I arbitrarily chose /root/ansible/slackware as my working directory. YMMV, so adjust accordingly.
#
# NOTE: I am not including sbopkg, sbotools nor slackpkg+ files, you'll need to get those on your own,
# and update the version listed as needed.

- hosts: '{{ hosts }}'
  remote_user: root
  tasks:

    # transfer account basics
    # you'll want to at least create these files (or comment out the plays), or copy your own in place
    - copy: src=/root/ansible/slackware/.profile  dest=/root/.profile owner=root group=wheel mode=0744
    - copy: src=/root/ansible/slackware/.bashrc   dest=/root/.bashrc  owner=root group=wheel mode=0744
    - copy: src=/root/ansible/slackware/.vimrc    dest=/root/.vimrc   owner=root group=wheel mode=0744

    - file: path=/root/bin      owner=root group=wheel mode=0775 state=directory
    - file: path=/root/temp     owner=root group=wheel mode=0775 state=directory
    - file: path=/root/sbo      owner=root group=wheel mode=0775 state=directory
    - file: path=/root/ansible  owner=root group=wheel mode=0775 state=directory
    - file: path=/root/programs owner=root group=wheel mode=0775 state=directory

    # sbopkg, in case we need to install any one-offs
    - copy: src=/root/ansible/slackware/sbopkg-0.37.1-noarch-1_wsr.tgz \
            dest=/root/programs/sbopkg-0.37.1-noarch-1_wsr.tgz  owner=root group=wheel mode=0744
    - raw: 'installpkg /root/programs/sbopkg-0.37.1-noarch-1_wsr.tgz'

    # sbotools, to make that job even easier :-)
    - copy: src=/root/ansible/slackware/sbotools-1.9-noarch-1_SBo.tgz \
            dest=/root/programs/sbotools-1.9-noarch-1_SBo.tgz  owner=root group=wheel mode=0744
    - raw: 'installpkg /root/programs/sbotools-1.9-noarch-1_SBo.tgz'
    - raw: 'sbosnap fetch'
      register: sbosnap
      ignore_errors: True
    - raw: 'sbosnap update'
      when: sbosnap|failed

    # ansible, so we can use that whenever possible from now on
    - raw: 'sboinstall -r pycrypto ecdsa paramiko PyYAML pysetuptools MarkupSafe Jinja2 httplib2 ansible'

    # slackpkg+ will enable us to install precompiled sbo package :-)
    # NOTE: uncomment this stanza if you want to install slackpkg+ on your system (some folks don't want this, so we leave it as an option).
    #- copy: src=/root/ansible/slackware/slackpkg+-1.6.1p2-noarch-1mt.txz \
    #  dest=/root/programs/slackpkg+-1.6.1p2-noarch-1mt.txz  owner=root group=wheel mode=0744
    #- raw: 'installpkg /root/programs/slackpkg+-1.6.1p2-noarch-1mt.txz'
    #- raw: 'slackpkg update gpg'
    
